import os
from datetime import datetime
from .models import Peripheral
from .errors import CodeGenError

WIDTH_TO_CTYPE = {8: "uint8_t", 16: "uint16_t", 32: "uint32_t", 64: "uint64_t"}


def _reg_ctype(register_width: int) -> str:
    ctype = WIDTH_TO_CTYPE.get(register_width)
    if ctype is None:
        raise CodeGenError(f"Unsupported register width: {register_width} (expected 8/16/32/64)")
    return ctype


def _generate_struct_body(peripheral: Peripheral) -> str:
    ctype = _reg_ctype(peripheral.register_width)
    lines = []
    sorted_regs = sorted(peripheral.registers, key=lambda r: r.offset)
    expected_offset = 0
    reserved_count = 0

    for reg in sorted_regs:
        if reg.offset > expected_offset:
            gap = reg.offset - expected_offset
            lines.append(
                f"    uint8_t  RESERVED{reserved_count}[{gap}];"
                f"  /* 0x{expected_offset:02X} - 0x{reg.offset - 1:02X} */"
            )
            reserved_count += 1

        access_comment = {"RO": "Read-Only", "WO": "Write-Only", "RW": "Read-Write"}.get(reg.access, reg.access)
        field_decl = f"    volatile {ctype} {reg.name};"
        lines.append(f"{field_decl:<38}/* Offset: 0x{reg.offset:02X}  ({access_comment}) */")
        expected_offset = reg.offset + reg.size_bytes

    return "\n".join(lines)


def _generate_bitfield_macros(peripheral: Peripheral) -> str:
    lines = []
    for reg in sorted(peripheral.registers, key=lambda r: r.offset):
        if not reg.bit_fields:
            continue
        lines.append(f"/* ---- {reg.name} bit-field macros ---- */")
        for bf in sorted(reg.bit_fields, key=lambda f: f.bit_start):
            prefix = f"{peripheral.name}_{reg.name}_{bf.name}"
            mask_val = ((1 << bf.bit_width) - 1) << bf.bit_start
            lines.append(f"#define {prefix}_Pos".ljust(32) + f"({bf.bit_start}U)")
            lines.append(f"#define {prefix}_Msk".ljust(32) + f"(0x{mask_val:X}U)")
            lines.append(f"#define {prefix}(x)".ljust(32) + f"(((x) << {prefix}_Pos) & {prefix}_Msk)")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generate_header(peripheral: Peripheral, output_path: str) -> None:
    guard = f"{peripheral.name.upper()}_H"
    struct_body = _generate_struct_body(peripheral)
    macros = _generate_bitfield_macros(peripheral)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    content = f"""/**
 * @file    {os.path.basename(output_path)}
 * @brief   Auto-generated register definitions for peripheral: {peripheral.name}
 *
 * WARNING: This file is auto-generated by the HSI Automation Engine.
 *          Do not edit manually - regenerate from the source config instead.
 *
 * Generated: {timestamp}
 */

#ifndef {guard}
#define {guard}

#include <stdint.h>

/* ================================================================== */
/* Peripheral: {peripheral.name}
/* Base Address: 0x{peripheral.base_address:08X}
/* ================================================================== */

typedef struct {{
{struct_body}
}} {peripheral.name}_Type;

#define {peripheral.name}   (({peripheral.name}_Type *) 0x{peripheral.base_address:08X}UL)

/* ================================================================== */
/* Bit-field Definitions                                              */
/* ================================================================== */

{macros}
#endif /* {guard} */
"""

    output_dir = os.path.dirname(output_path)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    try:
        with open(output_path, "w") as f:
            f.write(content)
    except OSError as e:
        raise CodeGenError(f"Failed to write header to '{output_path}': {e}")