/**
 * @file    uart0.h
 * @brief   Auto-generated register definitions for peripheral: UART0
 *
 * WARNING: This file is auto-generated by the HSI Automation Engine.
 *          Do not edit manually - regenerate from the source config instead.
 *
 * Generated: 2026-07-10 17:06:56
 */

#ifndef UART0_H
#define UART0_H

#include <stdint.h>

/* ================================================================== */
/* Peripheral: UART0
/* Base Address: 0x40011000
/* ================================================================== */

typedef struct {
    volatile uint32_t CTRL;           /* Offset: 0x00  (Read-Write) */
    volatile uint32_t STATUS;         /* Offset: 0x04  (Read-Only) */
    volatile uint32_t DATA;           /* Offset: 0x08  (Read-Write) */
} UART0_Type;

#define UART0   ((UART0_Type *) 0x40011000UL)

/* ================================================================== */
/* Bit-field Definitions                                              */
/* ================================================================== */

/* ---- CTRL bit-field macros ---- */
#define UART0_CTRL_ENABLE_Pos   (0U)
#define UART0_CTRL_ENABLE_Msk   (0x1U)
#define UART0_CTRL_ENABLE(x)    (((x) << UART0_CTRL_ENABLE_Pos) & UART0_CTRL_ENABLE_Msk)
#define UART0_CTRL_PARITY_Pos   (1U)
#define UART0_CTRL_PARITY_Msk   (0x6U)
#define UART0_CTRL_PARITY(x)    (((x) << UART0_CTRL_PARITY_Pos) & UART0_CTRL_PARITY_Msk)
#define UART0_CTRL_BAUD_SEL_Pos (4U)
#define UART0_CTRL_BAUD_SEL_Msk (0xF0U)
#define UART0_CTRL_BAUD_SEL(x)  (((x) << UART0_CTRL_BAUD_SEL_Pos) & UART0_CTRL_BAUD_SEL_Msk)

/* ---- STATUS bit-field macros ---- */
#define UART0_STATUS_TX_EMPTY_Pos(0U)
#define UART0_STATUS_TX_EMPTY_Msk(0x1U)
#define UART0_STATUS_TX_EMPTY(x)(((x) << UART0_STATUS_TX_EMPTY_Pos) & UART0_STATUS_TX_EMPTY_Msk)
#define UART0_STATUS_RX_READY_Pos(1U)
#define UART0_STATUS_RX_READY_Msk(0x2U)
#define UART0_STATUS_RX_READY(x)(((x) << UART0_STATUS_RX_READY_Pos) & UART0_STATUS_RX_READY_Msk)

#endif /* UART0_H */
